FROM nvcr.io/nvidia/tensorrt:23.01-py3

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libopencv-dev \
    && apt-get clean

WORKDIR /workspace

CMD ["/bin/bash"]
